### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by ppvan** [ppvan/psequel#1]
- [x] Allow query with params
- [x] #5
- [x] #7
- [x] Add keyboard short cut for oparations
- [x] About window and flatpak deployment
- [x] #14
- [x] #10
- [x] #12
- [x] Run query using Ctrl + <Enter>
- [x] #17
- [x] Query History
- [x] #21
- [x] #15

**Comment by ppvan** [comment]
Done
