### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by ppvan** [ppvan/psequel#50]
Things i want to add in next version:
- [x] Remove themes and add light/dark preview #52
- [ ] SSH turnel (i current duno wtf is this, but i'll try)
- [x] CSV import/export (many possible with postgres COPY command)
- [ ] implement an sql LSP client (not sure i have enough time)
- [x] Find a way to test the app -> not possible
- [x] Data cell should be copiable, context menu if needed

**Comment by khoinguyen2k** [comment]
How can you get these amount of stars?😲😎

**Comment by ppvan** [comment]
https://supabase.com/blog/postgres-language-server-implementing-parser

**Comment by ppvan** [comment]
Use a more robust CSV export: https://github.com/rgamble/libcsv/blob/master/csv.h

**Comment by ppvan** [comment]
Implement copy table DDL

**Comment by ppvan** [comment]
Using Github project from now on
